name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: adopt

      - name: Build with Gradle
        run: ./gradlew build -Prelease -PCI --stacktrace
